[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Remappings for dependencies
remappings = [
    "@uniswap/v3-core/=lib/v3-core/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
